// seed-guests.js
// Run: node seed-guests.js
// Requires: npm install @supabase/supabase-js

import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL  = 'YOUR_SUPABASE_URL'
const SUPABASE_KEY  = 'YOUR_SUPABASE_SERVICE_ROLE_KEY'  // use service role key for seed

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY)

const guests = [
  {
    "guest_number": 1,
    "name": "Susana Lo",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 2,
    "name": "David Chow",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 3,
    "name": "Hugo Chow",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 4,
    "name": "Grandma",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 5,
    "name": "Auntie7",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 6,
    "name": "Lisa",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": "No pork",
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 7,
    "name": "大伯伯",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 8,
    "name": "大伯娘",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 9,
    "name": "Edith Chau",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 10,
    "name": "肥仔",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 11,
    "name": "大姑",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 12,
    "name": "Christine YKT",
    "group_name": "Uni Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 13,
    "name": "Michael Chan Tsz King",
    "group_name": "Uni Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 14,
    "name": "Kwingthy Tsang",
    "group_name": "Uni Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 15,
    "name": "Miss Ku",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 16,
    "name": "Charlie Lee",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 17,
    "name": "Sukji",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 18,
    "name": "LST",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 19,
    "name": "Joey Lau Kawai",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 20,
    "name": "DearMe MPL",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 21,
    "name": "Jennifer Yu",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 22,
    "name": "Claire Yu",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 23,
    "name": "Toby Ho",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 24,
    "name": "Venus",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 25,
    "name": "Ho Shuk Ching",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 26,
    "name": "Phoebe Lai",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 27,
    "name": "LSY Alison",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 28,
    "name": "LK Sara",
    "group_name": "Secondary School Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 29,
    "name": "Flora Ding plus one",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 30,
    "name": "Flora Ding plus one",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 31,
    "name": "Mark Robson plus one",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 32,
    "name": "Mark Robson plus one",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 33,
    "name": "Evelyn Yau",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 34,
    "name": "Joanne Chan",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": "vegetarian",
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 35,
    "name": "Simon Yu",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 36,
    "name": "Carina Wu",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 37,
    "name": "Esther Yam",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 38,
    "name": "Rachel",
    "group_name": "Christy Ex-Colleague",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 39,
    "name": "Pui & BigG",
    "group_name": "Christy Church Friends",
    "side": "女方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 40,
    "name": "Sophia Yik & Joseph & Luca",
    "group_name": "Christy Church Friends",
    "side": "女方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 41,
    "name": "Grandma 婆婆",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 42,
    "name": "舅父",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 43,
    "name": "舅母",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 44,
    "name": "傑 & Tracy Family",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 45,
    "name": "傑 & Tracy Family",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 46,
    "name": "傑 & Tracy Family",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": true,
    "table_number": null
  },
  {
    "guest_number": 47,
    "name": "傑 & Tracy Family",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": true,
    "table_number": null
  },
  {
    "guest_number": 48,
    "name": "表姨",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 49,
    "name": "表姨丈",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 50,
    "name": "熙信",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 51,
    "name": "鳳姐",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 52,
    "name": "表舅公",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 53,
    "name": "Maria Lo Ka Man",
    "group_name": "Christy Church Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 54,
    "name": "Esther",
    "group_name": "Christy Church Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 55,
    "name": "Rosita",
    "group_name": "Christy Church Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 56,
    "name": "Lo Shing Chau",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 57,
    "name": "Lo Shing Chau",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 58,
    "name": "Lai Kam Biu",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 59,
    "name": "Lai Kam Biu",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 60,
    "name": "Lee Chi Wah",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 61,
    "name": "Lee Chi Wah",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 62,
    "name": "Wu Man Kit",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 63,
    "name": "Wu Man Kit",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 64,
    "name": "Wong Shu Tong",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 65,
    "name": "Chris Fung",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 66,
    "name": "Li Kwok Kit",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 67,
    "name": "Li Kwok Kit",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 68,
    "name": "Wong Ping Keung",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 69,
    "name": "Kelvin Lo",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 70,
    "name": "Ramen Ma",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 71,
    "name": "Tommy Hui",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 72,
    "name": "Yick Kin Wah & Shirely Cheung & Lok",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 73,
    "name": "Yick Kin Wah & Shirely Cheung & Lok",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 74,
    "name": "Yick Kin Wah & Shirely Cheung & Lok",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 75,
    "name": "William Tsang & Phoneix Lee",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 76,
    "name": "William Tsang & Phoneix Lee",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 77,
    "name": "Anthony Yip and Family",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 78,
    "name": "Anthony Yip and Family",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 79,
    "name": "Anthony Yip and Family",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": true,
    "table_number": null
  },
  {
    "guest_number": 80,
    "name": "Anthony Yip and Family",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": true,
    "table_number": null
  },
  {
    "guest_number": 81,
    "name": "Ho Yuk Ha",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 82,
    "name": "Mrs Yau & Agnes Yau",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 83,
    "name": "Mrs Yau & Agnes Yau",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 84,
    "name": "Andrew Wong & Teresa Yau",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 85,
    "name": "Andrew Wong & Teresa Yau",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 86,
    "name": "Biddy & Mother",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 87,
    "name": "Biddy & Mother",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 88,
    "name": "Tai Wai Fu",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 89,
    "name": "Portia Young",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 90,
    "name": "Franca Siu",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 91,
    "name": "Rita Kong",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 92,
    "name": "Alan Kam",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 93,
    "name": "大表姐 （穗禾苑）",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 94,
    "name": "Auntie Lisa Au （三舅婆）",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 95,
    "name": "Candy Mak and family (表姑姐)",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 96,
    "name": "Candy Mak and family",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 97,
    "name": "Chris Mak and family (表叔)",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 98,
    "name": "Chris Mak and family",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 99,
    "name": "Chris Mak and family",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 100,
    "name": "Karen Chan",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 101,
    "name": "Jeanette Chan",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 102,
    "name": "Anita Han",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 103,
    "name": "Virgina Lau",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 104,
    "name": "Virgina Lau",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 105,
    "name": "Yun Tak Keung & wife",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 106,
    "name": "Yun Tak Keung & wife",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 107,
    "name": "Gloria Szeto",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 108,
    "name": "Maria Fan",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 109,
    "name": "Wendy Foo",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 110,
    "name": "Marie Kwong",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 111,
    "name": "Selina Mak",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 112,
    "name": "Sharry Tong",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 113,
    "name": "Evelyn Li",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 114,
    "name": "Dick Chan",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 115,
    "name": "Maria Lo",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 116,
    "name": "Marco Chan",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 117,
    "name": "Adrian Lake & Nice Chan",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 118,
    "name": "Adrian Lake & Nice Chan",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 119,
    "name": "Ben Lo",
    "group_name": "Christy Relatives",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 120,
    "name": "Alice Wong & So Kwok Hung",
    "group_name": "Christy Mom Friends",
    "side": "女方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 121,
    "name": "Cat 姐",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 122,
    "name": "Cat 姐",
    "group_name": "Christy Dad Friends",
    "side": "女方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 123,
    "name": "Mitch Mom",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 124,
    "name": "Dalen",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 125,
    "name": "Vivian Ngai",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 126,
    "name": "Sam Li",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 127,
    "name": "Ben",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 128,
    "name": "Toby",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 129,
    "name": "Elaine",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 130,
    "name": "Jaysley Hung",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": "No beef",
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 131,
    "name": "Jenifer Gugufa",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 132,
    "name": "Carol Tam",
    "group_name": "Uni Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 133,
    "name": "Heather",
    "group_name": "Uni Friends",
    "side": "男方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 134,
    "name": "Austin",
    "group_name": "Uni Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 135,
    "name": "Isabel Tam",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": "No red meat",
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 136,
    "name": "Steven Leung",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 137,
    "name": "Aggie",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 138,
    "name": "Juddy",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 139,
    "name": "SoSo",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 140,
    "name": "CCP Vivian",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 141,
    "name": "Anthony",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 142,
    "name": "Pinky Chiu",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": "No beef",
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 143,
    "name": "Andi & Fung",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 144,
    "name": "Andi & Fung",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 145,
    "name": "Steve Yip",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 146,
    "name": "Shirley",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 147,
    "name": "Chu jai Howard",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 148,
    "name": "Roku",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 149,
    "name": "Adelia Su",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 150,
    "name": "Mickey Wong",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "No",
    "rsvp_status": "No",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 151,
    "name": "Katie",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 152,
    "name": "Mark Chan",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 153,
    "name": "Veron Ma",
    "group_name": "UK Friends",
    "side": "女方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 154,
    "name": "Elvin",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 155,
    "name": "Lena",
    "group_name": "UK Friends (China)",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 156,
    "name": "Charli Z",
    "group_name": "UK Friends (China)",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 157,
    "name": "Janet",
    "group_name": "UK Friends (China)",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 158,
    "name": "Charles",
    "group_name": "UK Friends (China)",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 159,
    "name": "David",
    "group_name": "UK Friends (China)",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 160,
    "name": "XY",
    "group_name": "UK Friends (China)",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 161,
    "name": "Wu",
    "group_name": "UK Friends (China)",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 162,
    "name": "77",
    "group_name": "UK Friends (China)",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 163,
    "name": "Michael Lam",
    "group_name": "Secondary School Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 164,
    "name": "Kenneth Fung",
    "group_name": "Secondary School Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 165,
    "name": "Wong Man Chun",
    "group_name": "Secondary School Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 166,
    "name": "Wong Man Chun Mom",
    "group_name": "Mitch Mom Friends",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 167,
    "name": "Minnie Choi",
    "group_name": "Secondary School Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 168,
    "name": "Calvin Tang",
    "group_name": "Secondary School Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 169,
    "name": "Winki",
    "group_name": "Foodie Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 170,
    "name": "Leo",
    "group_name": "Foodie Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 171,
    "name": "Wini",
    "group_name": "Foodie Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 172,
    "name": "Peter",
    "group_name": "Foodie Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 173,
    "name": "CanCan",
    "group_name": "Foodie Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 174,
    "name": "Erica",
    "group_name": "Foodie Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 175,
    "name": "Sam",
    "group_name": "Foodie Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 176,
    "name": "Kelly",
    "group_name": "Foodie Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 177,
    "name": "Billy",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 178,
    "name": "Gina",
    "group_name": "HK Macau Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 179,
    "name": "Takaya",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 180,
    "name": "Ella",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 181,
    "name": "Ise Jun",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 182,
    "name": "富士先生",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 183,
    "name": "DC",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 184,
    "name": "Casey",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 185,
    "name": "Max",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 186,
    "name": "Joyce",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 187,
    "name": "黑柴",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 188,
    "name": "Gentle",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 189,
    "name": "Gentle老婆",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 190,
    "name": "Ben Iu",
    "group_name": "Mitch Colleague",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 191,
    "name": "Kalista",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 192,
    "name": "Charlene",
    "group_name": "UK Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 193,
    "name": "紅紅姐姐",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 194,
    "name": "菊菊阿姨",
    "group_name": "Mitch Family",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 195,
    "name": "Zeno",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 196,
    "name": "Charine",
    "group_name": "Mitch Work Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 197,
    "name": "Jia Jhang",
    "group_name": "Uni Friends",
    "side": "男方",
    "invited": "Yes",
    "rsvp_status": "Yes",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  },
  {
    "guest_number": 198,
    "name": "Huang Jia",
    "group_name": "Uni Friends",
    "side": "男方",
    "invited": "Pending",
    "rsvp_status": "Pending",
    "dietary": null,
    "is_kid": false,
    "table_number": null
  }
]

async function seed() {
  console.log(`Seeding ${guests.length} guests...`)
  const { data, error } = await supabase
    .from('guests')
    .upsert(guests, { onConflict: 'guest_number' })
  if (error) { console.error('Error:', error); process.exit(1) }
  console.log(`✓ Seeded ${guests.length} guests successfully`)
}

seed()
