'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');
const { pgcrypto } = require('@electric-sql/pglite/contrib/pgcrypto');
const Live = require('../live-captions-client.js');
const { CaptionStore } = require('../lib/captions/store.cjs');
const { CaptionGateway, GatewaySession } = require('../lib/captions/gateway.cjs');

const migrationPath = path.join(__dirname, '..', 'supabase', 'migrations', '2026-10-02_live_captions.sql');
const guestLinksPath = path.join(__dirname, '..', 'supabase', 'migrations', '2026-10-02_live_captions_guest_links.sql');

async function database({ supabaseExtensions = false } = {}) {
  const db = new PGlite({ extensions: { pgcrypto } });
  // Supabase installs pgcrypto in its own `extensions` schema; by default it lands in public here.
  if (supabaseExtensions) await db.exec(`CREATE SCHEMA extensions; CREATE EXTENSION pgcrypto SCHEMA extensions;`);
  await db.exec(`
    CREATE ROLE anon;
    CREATE ROLE authenticated;
    CREATE ROLE service_role;
    CREATE SCHEMA auth;
    CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
      SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
    $$;
    CREATE OR REPLACE FUNCTION auth.role() RETURNS text LANGUAGE sql STABLE AS $$
      SELECT nullif(current_setting('request.jwt.claim.role', true), '')
    $$;
    CREATE OR REPLACE FUNCTION auth.email() RETURNS text LANGUAGE sql STABLE AS $$
      SELECT nullif(current_setting('request.jwt.claim.email', true), '')
    $$;
    GRANT USAGE ON SCHEMA auth TO authenticated, service_role;
    GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA auth TO authenticated, service_role;
    CREATE OR REPLACE FUNCTION is_admin() RETURNS boolean LANGUAGE sql STABLE AS $$
      SELECT coalesce(auth.email(),'') IN ('christychowtc@gmail.com','mitchell.tsui.mc@gmail.com')
    $$;
    CREATE SCHEMA realtime;
    CREATE TABLE realtime.messages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, topic text, extension text);
    ALTER TABLE realtime.messages ENABLE ROW LEVEL SECURITY;
    GRANT USAGE ON SCHEMA realtime TO authenticated, service_role;
    GRANT SELECT, INSERT ON realtime.messages TO authenticated;
    CREATE OR REPLACE FUNCTION realtime.topic() RETURNS text LANGUAGE sql STABLE AS $$
      SELECT nullif(current_setting('realtime.topic', true), '')
    $$;
  `);
  await db.exec(await fs.readFile(migrationPath, 'utf8'));
  await db.exec(await fs.readFile(guestLinksPath, 'utf8'));
  return db;
}

async function asService(db) {
  await db.exec(`SELECT set_config('request.jwt.claim.role','service_role',false);`);
}

function storeResponse(status, payload) {
  return { ok: status >= 200 && status < 300, status,
    text: async () => payload === undefined ? '' : JSON.stringify(payload) };
}

function makeStoreFetch(db) {
  const jsonArguments = new Set(['p_source_segment','p_segment','p_captions','p_payloads','p_details_safe']);
  const setFunctions = new Set(['caption_claim_outbox','caption_claim_approved_reviews']);
  return async (url, options = {}) => {
    const match = /^\/rest\/v1\/rpc\/([a-z_]+)$/.exec(new URL(url).pathname);
    if (!match) return storeResponse(404, { code: 'not_found' });
    const name = match[1];
    assert.match(name, /^caption_[a-z_]+$/);
    try {
      await asService(db);
      const args = options.body ? JSON.parse(options.body) : {};
      const values = [];
      const named = Object.entries(args).map(([key, value], index) => {
        values.push(jsonArguments.has(key) ? JSON.stringify(value) : value);
        return `${key} => $${index + 1}${jsonArguments.has(key) ? '::jsonb' : ''}`;
      });
      const returnsSet = setFunctions.has(name);
      const sql = returnsSet ? `SELECT * FROM ${name}(${named.join(',')})`
        : `SELECT ${name}(${named.join(',')}) AS value`;
      const result = await db.query(sql, values);
      return storeResponse(200, returnsSet ? result.rows : result.rows[0]?.value);
    } catch (error) {
      return storeResponse(error.code === '42501' ? 403 : 400, { code: error.code || 'db_error' });
    }
  };
}

test('migration installs on a real local PostgreSQL engine and is idempotent', async t => {
  const db = await database();
  t.after(() => db.close());
  await db.exec(await fs.readFile(migrationPath, 'utf8'));
  const tables = await db.query(`SELECT count(*)::int AS count FROM information_schema.tables WHERE table_schema='public' AND table_name LIKE 'caption_%'`);
  assert.equal(tables.rows[0].count, 14);
});

test('tickets and invites work with pgcrypto in the extensions schema, as Supabase installs it', async t => {
  const db = await database({ supabaseExtensions: true });
  t.after(() => db.close());
  const placed = await db.query(`SELECT n.nspname FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace WHERE e.extname='pgcrypto'`);
  assert.deepEqual(placed.rows, [{ nspname: 'extensions' }]);
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Supabase layout','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  const invite = (await db.query(`SELECT caption_create_invite($1,now()+interval '1 day',2) AS value`, [event.event_id])).rows[0].value;
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false); SELECT set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',false); SELECT set_config('request.jwt.claim.email','christychowtc@gmail.com',false);`);
  const ticket = (await db.query(`SELECT caption_issue_uplink_ticket($1,'https://wedding.test') AS value`, [run.run_id])).rows[0].value;
  const consumed = (await db.query(`SELECT caption_consume_uplink_ticket($1,'https://wedding.test') AS value`, [ticket.token])).rows[0].value;
  assert.equal(consumed.run_id, run.run_id);
  await db.exec(`SELECT set_config('request.jwt.claim.sub','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',false); SELECT set_config('request.jwt.claim.email','',false);`);
  const redeemed = (await db.query(`SELECT caption_redeem_invite($1,$2) AS value`, [event.event_id, invite.token])).rows[0].value;
  assert.equal(redeemed.role, 'guest');
});

test('the guest link migration applies after the original, both re-apply cleanly, and only the service role may call it', async t => {
  const db = await database({ supabaseExtensions: true });
  t.after(() => db.close());
  for (const file of [migrationPath, guestLinksPath, guestLinksPath, migrationPath]) await db.exec(await fs.readFile(file, 'utf8'));
  const functions = await db.query(`SELECT count(*)::int AS count FROM pg_proc WHERE proname='caption_guest_access'`);
  assert.equal(functions.rows[0].count, 1);
  const privilege = await db.query(`SELECT has_function_privilege('anon','public.caption_guest_access(uuid,text)','EXECUTE') AS anon,
    has_function_privilege('authenticated','public.caption_guest_access(uuid,text)','EXECUTE') AS authenticated,
    has_function_privilege('service_role','public.caption_guest_access(uuid,text)','EXECUTE') AS service`);
  assert.deepEqual(privilege.rows[0], { anon: false, authenticated: false, service: true });
  for (const role of ['anon', 'authenticated']) {
    await db.exec(`SET ROLE ${role}`);
    try {
      await assert.rejects(db.query(`SELECT caption_guest_access('11111111-1111-4111-8111-111111111111','token')`), /permission denied/);
    } finally { await db.exec(`RESET ROLE`); }
  }
});

test('guest access admits only an active, unexpired link for its own event, returns the current run and writes nothing', async t => {
  const db = await database({ supabaseExtensions: true });
  t.after(() => db.close());
  await asService(db);
  const access = async (eventId, token) => (await db.query(`SELECT caption_guest_access($1,$2) AS value`, [eventId, token])).rows[0].value;
  const refused = (eventId, token) => assert.rejects(db.query(`SELECT caption_guest_access($1,$2)`, [eventId, token]),
    error => error.code === '28000' && /guest link unavailable/.test(error.message));
  const event = (await db.query(`SELECT caption_create_event('Guest links','{}') AS value`)).rows[0].value;
  const other = (await db.query(`SELECT caption_create_event('Other wedding','{}') AS value`)).rows[0].value;
  const invite = (await db.query(`SELECT caption_create_invite($1,now()+interval '1 day',1) AS value`, [event.event_id])).rows[0].value;
  const otherInvite = (await db.query(`SELECT caption_create_invite($1,now()+interval '1 day',1) AS value`, [other.event_id])).rows[0].value;
  const before = await access(event.event_id, invite.token);
  assert.equal(before.run_id, null); assert.equal(before.event_id, event.event_id); assert.ok(before.expires_at);
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  for (let read = 0; read < 3; read += 1) assert.equal((await access(event.event_id, invite.token)).run_id, run.run_id, 'max_uses 1 is not enforced');
  const counted = await db.query(`SELECT use_count FROM caption_invites WHERE id=$1`, [invite.invite_id]);
  assert.equal(counted.rows[0].use_count, 0);
  await refused(event.event_id, 'not-the-token');
  await refused(event.event_id, otherInvite.token);
  await refused(other.event_id, invite.token);
  await refused(event.event_id, null);
  await db.query(`UPDATE caption_invites SET active=false WHERE id=$1`, [invite.invite_id]);
  await refused(event.event_id, invite.token);
  await db.query(`UPDATE caption_invites SET active=true, created_at=now()-interval '2 days', expires_at=now()-interval '1 second' WHERE id=$1`, [invite.invite_id]);
  await refused(event.event_id, invite.token);
  assert.equal((await access(other.event_id, otherInvite.token)).run_id, null);
});

test('the service role can read an event row directly for the open-run lookup, and anon cannot', async t => {
  const db = await database();
  t.after(() => db.close());
  const privilege = await db.query(`SELECT has_table_privilege('service_role','public.caption_events','SELECT') AS service,
    has_table_privilege('anon','public.caption_events','SELECT') AS anon`);
  assert.deepEqual(privilege.rows[0], { service: true, anon: false });
  await db.exec(`INSERT INTO caption_events(title) VALUES ('Lookup')`);
  await db.exec(`SET ROLE service_role`);
  try {
    const rows = await db.query(`SELECT current_run_id FROM public.caption_events WHERE title='Lookup'`);
    assert.deepEqual(rows.rows, [{ current_run_id: null }]);
  } finally { await db.exec(`RESET ROLE`); }
});

test('final persistence and outbox enqueue are atomic, idempotent and sequence-authoritative', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const created = await db.query(`SELECT caption_create_event('Test event','{}') AS value`);
  const eventId = created.rows[0].value.event_id;
  const started = await db.query(`SELECT caption_start_run($1,'live') AS value`, [eventId]);
  const run = started.rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=9, lease_expires_at=now()+interval '5 minutes' WHERE id=$1`, [run.run_id]);
  const segmentId = '22222222-2222-4222-8222-222222222222';
  const args = [run.run_id, 1, 9,
    JSON.stringify({ segmentId, segmentOrder: 0, sourceRevision: 1, text: '多謝大家', status: 'final' }),
    JSON.stringify([{ language: 'en', text: 'Thank you, everyone.', status: 'final', captionRevision: 1, sourceRevision: 1, origin: 'ai_live' }]),
    JSON.stringify([{ language: 'en', idempotencyKey: 'seg-1-en', payload: { type: 'caption.batch' } }]), 'seg-1'];
  const result = await db.query(`SELECT caption_persist_final_and_enqueue($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7) AS value`, args);
  assert.equal(Number(result.rows[0].value.message_sequences.en), 1);
  const outbox = await db.query(`SELECT payload FROM caption_outbox_events WHERE run_id=$1`, [run.run_id]);
  assert.equal(outbox.rows.length, 1);
  assert.equal(Number(outbox.rows[0].payload.messageSeq), 1);
  assert.equal(outbox.rows[0].payload.modeGeneration, 1);
  const retry = await db.query(`SELECT caption_persist_final_and_enqueue($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7) AS value`, args);
  assert.equal(Number(retry.rows[0].value.message_sequences.en), 1);
  const jaArgs = [run.run_id, 1, 9, args[3],
    JSON.stringify([{ language: 'ja', text: '皆様、ありがとうございます。', status: 'final', captionRevision: 1, sourceRevision: 1, origin: 'ai_live' }]),
    JSON.stringify([{ language: 'ja', idempotencyKey: 'seg-1-ja', payload: { type: 'caption.batch' } }]), 'seg-1-ja'];
  const japanese = await db.query(`SELECT caption_persist_final_and_enqueue($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7) AS value`, jaArgs);
  assert.equal(Number(japanese.rows[0].value.message_sequences.ja), 1);
  const cursors = await db.query(`SELECT language,message_seq FROM caption_channel_sequences WHERE run_id=$1 ORDER BY language`, [run.run_id]);
  assert.deepEqual(cursors.rows.map(row => ({ language: row.language, message_seq: Number(row.message_seq) })), [
    { language: 'en', message_seq: 0 }, { language: 'ja', message_seq: 0 }
  ]);
  const claimed = await db.query(`SELECT language,payload FROM caption_claim_outbox($1,10,'worker',1,9) ORDER BY language`, [run.run_id]);
  assert.equal(claimed.rows.length, 2);
  assert.deepEqual(claimed.rows.map(row => [row.language, Number(row.payload.messageSeq)]), [['en',1],['ja',1]]);
  const published = await db.query(`SELECT language,message_seq FROM caption_channel_sequences WHERE run_id=$1 ORDER BY language`, [run.run_id]);
  assert.deepEqual(published.rows.map(row => ({ language: row.language, message_seq: Number(row.message_seq) })), [
    { language: 'en', message_seq: 1 }, { language: 'ja', message_seq: 1 }
  ]);
  const counts = await db.query(`SELECT (SELECT count(*) FROM caption_source_segments)::int segments,(SELECT count(*) FROM caption_captions)::int captions,(SELECT count(*) FROM caption_outbox_events)::int outbox`);
  assert.deepEqual(counts.rows[0], { segments: 1, captions: 2, outbox: 2 });
});

test('successful recovery advances unavailable caption revision and blocks same-source downgrade', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Unavailable recovery','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=3,lease_expires_at=now()+interval '5 minutes' WHERE id=$1`, [run.run_id]);
  const sid = '23232323-2323-4232-8232-232323232323';
  const source = { segmentId:sid,segmentOrder:0,sourceRevision:1,text:'source',status:'final' };
  const payload = update => [{ language:'en',idempotencyKey:`${update.status}-en`,payload:{
    schemaVersion:1,type:'caption.batch',eventId:event.event_id,runId:run.run_id,modeGeneration:1,
    channelEpoch:run.channel_epoch,messageSeq:1,language:'en',updates:[{ segmentId:sid,segmentOrder:0,...update }]
  } }];
  const unavailable = { language:'en',text:'',status:'unavailable',captionRevision:1,sourceRevision:1,origin:'ai_live' };
  await db.query(`SELECT caption_persist_final_and_enqueue($1,1,3,$2::jsonb,$3::jsonb,$4::jsonb,'unavailable')`,
    [run.run_id,JSON.stringify(source),JSON.stringify([unavailable]),JSON.stringify(payload(unavailable))]);
  const first = await db.query(`SELECT * FROM caption_claim_outbox($1,10,'worker-a',1,3)`, [run.run_id]);
  const reducer = new Live.CaptionStore();
  assert.equal(reducer.merge(first.rows[0].payload), true);
  assert.equal(reducer.segments('en')[0].status, 'unavailable');

  const recovered = { language:'en',text:'Recovered translation',status:'final',captionRevision:1,sourceRevision:1,origin:'ai_live' };
  const saved = (await db.query(`SELECT caption_persist_final_and_enqueue($1,1,3,$2::jsonb,$3::jsonb,$4::jsonb,'recovered') AS value`,
    [run.run_id,JSON.stringify(source),JSON.stringify([recovered]),JSON.stringify(payload(recovered))])).rows[0].value;
  assert.equal(saved.outbox_count, 1);
  const second = await db.query(`SELECT * FROM caption_claim_outbox($1,10,'worker-b',1,3)`, [run.run_id]);
  assert.equal(Number(second.rows[0].payload.updates[0].captionRevision), 2);
  assert.equal(reducer.merge(second.rows[0].payload), true);
  assert.deepEqual(reducer.segments('en').map(item => ({ text:item.text,status:item.status,captionRevision:item.captionRevision })),
    [{ text:'Recovered translation',status:'final',captionRevision:2 }]);

  const downgrade = { ...unavailable, captionRevision:2 };
  const rejected = (await db.query(`SELECT caption_persist_final_and_enqueue($1,1,3,$2::jsonb,$3::jsonb,$4::jsonb,'downgrade') AS value`,
    [run.run_id,JSON.stringify(source),JSON.stringify([downgrade]),JSON.stringify(payload(downgrade))])).rows[0].value;
  assert.equal(rejected.outbox_count, 0);
  const stored = await db.query(`SELECT text,status,caption_revision FROM caption_captions WHERE run_id=$1 AND segment_id=$2 AND language='en'`,
    [run.run_id,sid]);
  assert.deepEqual(stored.rows[0], { text:'Recovered translation',status:'final',caption_revision:2 });
});

test('stale generation cannot persist or enqueue a final caption', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Fence test','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=4 WHERE id=$1`, [run.run_id]);
  await assert.rejects(db.query(`SELECT caption_persist_final_and_enqueue($1,99,4,$2::jsonb,'[]','[]','stale')`, [run.run_id, JSON.stringify({ segmentId: '33333333-3333-4333-8333-333333333333', segmentOrder: 0, sourceRevision: 1, text: 'x' })]), /stale publisher generation or fence/);
  const count = await db.query(`SELECT count(*)::int AS count FROM caption_source_segments`);
  assert.equal(count.rows[0].count, 0);
});

test('invite redemption stores only the token hash and grants only the authenticated user', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Invite test','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`,[event.event_id])).rows[0].value;
  const invite = (await db.query(`SELECT caption_create_invite($1,now()+interval '1 day',2) AS value`, [event.event_id])).rows[0].value;
  assert.ok(invite.token.length >= 40);
  const stored = await db.query(`SELECT token_hash, encode(token_hash,'escape') AS encoded FROM caption_invites`);
  assert.notEqual(stored.rows[0].encoded, invite.token);
  const userId = '11111111-1111-4111-8111-111111111111';
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false); SELECT set_config('request.jwt.claim.sub','${userId}',false);`);
  const redeemed=(await db.query(`SELECT caption_redeem_invite($1,$2) AS value`, [event.event_id, invite.token])).rows[0].value;
  assert.equal(redeemed.run_id,run.run_id);
  const member = await db.query(`SELECT user_id::text, role FROM caption_event_members`);
  assert.deepEqual(member.rows[0], { user_id: userId, role: 'guest' });
});

test('guest membership receives only its caption topic and cannot read scripts or glossary', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('RLS test','{}') AS value`)).rows[0].value;
  const invite = (await db.query(`SELECT caption_create_invite($1,now()+interval '1 day',2) AS value`, [event.event_id])).rows[0].value;
  const userId = '11111111-1111-4111-8111-111111111111';
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false); SELECT set_config('request.jwt.claim.sub','${userId}',false);`);
  await db.query(`SELECT caption_redeem_invite($1,$2)`, [event.event_id, invite.token]);
  const topics = await db.query(`SELECT caption_can_receive_topic($1) receive,caption_can_send_topic($1) send,caption_can_receive_topic($2) other`, [`caption:${event.event_id}:en`, 'caption:00000000-0000-0000-0000-000000000099:en']);
  assert.deepEqual(topics.rows[0], { receive: true, send: false, other: false });
  await db.exec(`SET ROLE authenticated`);
  const hidden = await db.query(`SELECT (SELECT count(*) FROM caption_scripts)::int scripts,(SELECT count(*) FROM caption_glossary_entries)::int glossary`);
  assert.deepEqual(hidden.rows[0], { scripts: 0, glossary: 0 });
  await db.exec(`RESET ROLE`);
});

test('approved script corrections are fence-claimed once and completed explicitly', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Review test','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=8,lease_expires_at=now()+interval '5 minutes' WHERE id=$1`, [run.run_id]);
  const segmentId = '44444444-4444-4444-8444-444444444444';
  const review = (await db.query(`SELECT caption_record_script_review($1,$2,4,1,'原文','修正文',NULL,'provider-4') AS value`, [run.run_id, segmentId])).rows[0].value;
  await db.query(`SELECT caption_review_suggestion($1,'accepted',NULL)`, [review.review_id]);
  const claimed = await db.query(`SELECT * FROM caption_claim_approved_reviews($1,1,8,'worker-a',10)`, [run.run_id]);
  assert.equal(claimed.rows.length, 1);
  assert.equal(Number(claimed.rows[0].segment_order), 4);
  assert.equal(claimed.rows[0].provider_item_id, 'provider-4');
  assert.equal((await db.query(`SELECT count(*)::int count FROM caption_claim_approved_reviews($1,1,8,'worker-b',10)`, [run.run_id])).rows[0].count, 0);
  const completed = (await db.query(`SELECT caption_complete_approved_review($1,'worker-a',NULL) AS value`, [review.review_id])).rows[0].value;
  assert.equal(completed.applied, true);
});

test('actual store normalizes claimed review id so gateway checkpoints and queues all languages', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Review contract','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=18,lease_expires_at=now()+interval '5 minutes' WHERE id=$1`, [run.run_id]);
  const segmentId = '45454545-4545-4545-8545-454545454545';
  const review = (await db.query(`SELECT caption_record_script_review($1,$2,7,2,'old','corrected',NULL,'provider-7') AS value`,
    [run.run_id, segmentId])).rows[0].value;
  await db.query(`SELECT caption_review_suggestion($1,'accepted',NULL)`, [review.review_id]);

  const store = new CaptionStore({ supabaseUrl: 'https://local.supabase.test', serviceRoleKey: 'server-secret',
    fetchImpl: makeStoreFetch(db) });
  let claimedRows;
  const claim = store.claimApprovedReviews.bind(store);
  store.claimApprovedReviews = async input => (claimedRows = await claim(input));
  const translated = [];
  const published = [];
  const gateway = new CaptionGateway({ store, allowedOrigins: ['https://wedding.test'],
    asrFactory: () => ({ close() {} }),
    translator: { async translate({ language, currentSegment }) {
      translated.push(language); assert.equal(currentSegment, 'corrected'); return { text: `${language}-corrected` };
    } },
    publisher: { async publish(topic, eventName, payload) { published.push({ topic, eventName, payload }); } },
    config: { heartbeatMs: 100000, rotateAfterMs: 100000, shutdownAfterMs: 110000 } });
  const socket = { readyState: 1, sent: [], send(value) { this.sent.push(JSON.parse(value)); }, close() {} };
  const session = new GatewaySession({ gateway, socket, origin: 'https://wedding.test' });
  session.context = { eventId: event.event_id, runId: run.run_id, modeGeneration: 1,
    fencingToken: 18, channelEpoch: run.channel_epoch };
  session.glossary = [];

  await session.pollApprovedReviews();
  await session.lanes.onIdle();
  assert.equal(claimedRows.length, 1);
  assert.equal(claimedRows[0].reviewId, review.review_id);
  assert.deepEqual(new Set(translated), new Set(['en','ja','zh-CN']));
  const source = await db.query(`SELECT source_revision,text FROM caption_source_segments WHERE run_id=$1 AND segment_id=$2`,
    [run.run_id, segmentId]);
  assert.deepEqual(source.rows[0], { source_revision: 3, text: 'corrected' });
  const captions = await db.query(`SELECT language,text FROM caption_captions WHERE run_id=$1 AND segment_id=$2 ORDER BY language`,
    [run.run_id, segmentId]);
  assert.deepEqual(captions.rows, [
    { language:'en',text:'en-corrected' }, { language:'ja',text:'ja-corrected' },
    { language:'zh-CN',text:'zh-CN-corrected' }
  ]);
  assert.equal(published.length, 3);
  const applied = await db.query(`SELECT applied_at IS NOT NULL AS applied FROM caption_script_reviews WHERE id=$1`, [review.review_id]);
  assert.equal(applied.rows[0].applied, true);
  session.lanes.close();
});

test('guest RLS denies private tables, other events, writes, admin RPCs and Realtime send', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const own = (await db.query(`SELECT caption_create_event('Own','{}') AS value`)).rows[0].value;
  const other = (await db.query(`SELECT caption_create_event('Other','{}') AS value`)).rows[0].value;
  const ownRun = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [own.event_id])).rows[0].value;
  const otherRun = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [other.event_id])).rows[0].value;
  await db.query(`INSERT INTO caption_source_segments(run_id,segment_id,segment_order,source_revision,text,status) VALUES($1,'55555555-5555-4555-8555-555555555555',0,1,'source','final')`, [ownRun.run_id]);
  await db.query(`INSERT INTO caption_captions(run_id,segment_id,language,text,status,caption_revision,source_revision,origin) VALUES($1,'55555555-5555-4555-8555-555555555555','en','Own final','final',1,1,'ai_live')`, [ownRun.run_id]);
  await db.query(`INSERT INTO caption_scripts(event_id,title,content) VALUES($1,'Private','Secret script')`, [own.event_id]);
  await db.query(`INSERT INTO caption_glossary_entries(event_id,source_term) VALUES($1,'Private name')`, [own.event_id]);
  await db.query(`INSERT INTO caption_outbox_events(event_id,run_id,language,idempotency_key,payload) VALUES($1,$2,'en','private','{}')`, [own.event_id, ownRun.run_id]);
  const invite = (await db.query(`SELECT caption_create_invite($1,now()+interval '1 day',2) AS value`, [own.event_id])).rows[0].value;
  const userId = '11111111-1111-4111-8111-111111111111';
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false); SELECT set_config('request.jwt.claim.sub','${userId}',false); SELECT set_config('request.jwt.claim.email','guest@example.com',false);`);
  await db.query(`SELECT caption_redeem_invite($1,$2)`, [own.event_id, invite.token]);
  await db.exec(`SET ROLE authenticated`);
  const snapshot = (await db.query(`SELECT caption_snapshot($1,$2,'en') AS value`, [own.event_id, ownRun.run_id])).rows[0].value;
  assert.equal(snapshot.updates[0].text, 'Own final');
  await assert.rejects(db.query(`SELECT caption_snapshot($1,$2,'en')`, [other.event_id, otherRun.run_id]), /caption membership required/);
  const hidden = await db.query(`SELECT
    (SELECT count(*) FROM caption_source_segments)::int sources,
    (SELECT count(*) FROM caption_scripts)::int scripts,
    (SELECT count(*) FROM caption_glossary_entries)::int glossary,
    (SELECT count(*) FROM caption_invites)::int invites,
    (SELECT count(*) FROM caption_outbox_events)::int outbox,
    (SELECT count(*) FROM caption_captions)::int captions`);
  assert.deepEqual(hidden.rows[0], { sources: 0, scripts: 0, glossary: 0, invites: 0, outbox: 0, captions: 0 });
  await assert.rejects(db.query(`INSERT INTO caption_event_members(event_id,user_id,role) VALUES($1,$2,'admin')`, [own.event_id, userId]), /row-level security policy/);
  await assert.rejects(db.query(`INSERT INTO caption_captions(run_id,segment_id,language,text,status,caption_revision,source_revision,origin) VALUES($1,'55555555-5555-4555-8555-555555555555','ja','attack','final',1,1,'manual')`, [ownRun.run_id]), /row-level security policy/);
  await assert.rejects(db.query(`SELECT caption_start_run($1,'live')`, [own.event_id]), /permission denied/);
  await db.exec(`SELECT set_config('realtime.topic','caption:${own.event_id}:en',false)`);
  await assert.rejects(db.query(`INSERT INTO realtime.messages(topic,extension) VALUES($1,'broadcast')`, [`caption:${own.event_id}:en`]), /row-level security policy|permission denied/);
  await db.exec(`RESET ROLE`);
});

test('uplink tickets are origin-bound, single-use, expiring and fenced by takeover', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Ticket test','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  const userId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false); SELECT set_config('request.jwt.claim.sub','${userId}',false); SELECT set_config('request.jwt.claim.email','christychowtc@gmail.com',false);`);
  const first = (await db.query(`SELECT caption_issue_uplink_ticket($1,'https://wedding.test') AS value`, [run.run_id])).rows[0].value;
  const second = (await db.query(`SELECT caption_issue_uplink_ticket($1,'https://wedding.test') AS value`, [run.run_id])).rows[0].value;
  assert.notEqual(first.channel_epoch, second.channel_epoch);
  await assert.rejects(db.query(`SELECT caption_consume_uplink_ticket($1,'https://wedding.test')`, [first.token]), /publisher lease unavailable/);
  await assert.rejects(db.query(`SELECT caption_consume_uplink_ticket($1,'https://wrong.test')`, [second.token]), /uplink ticket unavailable/);
  const consumed = (await db.query(`SELECT caption_consume_uplink_ticket($1,'https://wedding.test') AS value`, [second.token])).rows[0].value;
  assert.equal(Number(consumed.fencing_token), 2);
  await assert.rejects(db.query(`SELECT caption_consume_uplink_ticket($1,'https://wedding.test')`, [second.token]), /uplink ticket unavailable/);
  const block = (await db.query(`SELECT caption_reserve_message_sequence_block($1,1,2,128) AS value`, [run.run_id])).rows[0].value;
  assert.deepEqual(block.ranges.en, { end: 128, start: 1 });
  const draft = (await db.query(`SELECT caption_checkpoint_draft($1,1,2,$2::jsonb,$3::jsonb) AS value`, [run.run_id,
    JSON.stringify({ segmentId:'77777777-7777-4777-8777-777777777777',segmentOrder:0 }),
    JSON.stringify([{ language:'en',sourceRevision:1,captionRevision:1,text:'draft',messageSeq:1 }])])).rows[0].value;
  assert.equal(Number(draft.message_sequences.en), 1);
  const third = (await db.query(`SELECT caption_issue_uplink_ticket($1,'https://wedding.test') AS value`, [run.run_id])).rows[0].value;
  const reset = await db.query(`SELECT message_seq,allocated_through FROM caption_channel_sequences WHERE run_id=$1 AND language='en'`, [run.run_id]);
  assert.deepEqual({ message_seq:Number(reset.rows[0].message_seq), allocated_through:Number(reset.rows[0].allocated_through) }, { message_seq:0, allocated_through:0 });
  await db.query(`UPDATE caption_uplink_tickets SET created_at=now()-interval '2 seconds',expires_at=now()-interval '1 second' WHERE token_hash=digest($1,'sha256')`, [third.token]);
  await assert.rejects(db.query(`SELECT caption_consume_uplink_ticket($1,'https://wedding.test')`, [third.token]), /uplink ticket unavailable/);
});

test('manual correction lock survives late AI and pause invalidates the publisher generation', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Correction test','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=5,lease_expires_at=now()+interval '5 minutes' WHERE id=$1`, [run.run_id]);
  const source = { segmentId: '66666666-6666-4666-8666-666666666666', segmentOrder: 0, sourceRevision: 1, text: 'source', status: 'final' };
  await db.query(`SELECT caption_persist_final_and_enqueue($1,1,5,$2::jsonb,$3::jsonb,'[]','initial')`, [run.run_id, JSON.stringify(source), JSON.stringify([{ language:'en', text:'AI old', status:'final', captionRevision:1, sourceRevision:1, origin:'ai_live' }])]);
  await db.query(`SELECT caption_manual_publish($1,'en','Operator correction',$2)`, [run.run_id, source.segmentId]);
  await db.query(`SELECT caption_persist_final_and_enqueue($1,1,5,$2::jsonb,$3::jsonb,'[]','late')`, [run.run_id, JSON.stringify({ ...source, sourceRevision:2, text:'source revised' }), JSON.stringify([{ language:'en', text:'AI late', status:'final', captionRevision:99, sourceRevision:2, origin:'ai_live' }])]);
  const caption = await db.query(`SELECT text,status,origin FROM caption_captions WHERE run_id=$1 AND segment_id=$2 AND language='en'`, [run.run_id, source.segmentId]);
  assert.deepEqual(caption.rows[0], { text: 'Operator correction', status: 'corrected', origin: 'manual' });
  await db.query(`SELECT caption_transition_run($1,'pause')`, [run.run_id]);
  await assert.rejects(db.query(`SELECT caption_checkpoint_source($1,1,5,$2::jsonb)`, [run.run_id, JSON.stringify(source)]), /stale publisher generation or fence/);
});

test('segment order reservation and source checkpoint survive before translation', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Recovery test','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`, [event.event_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=6,lease_expires_at=now()+interval '5 minutes' WHERE id=$1`, [run.run_id]);
  const first = (await db.query(`SELECT caption_reserve_segment_order($1,1,6) AS value`, [run.run_id])).rows[0].value;
  const second = (await db.query(`SELECT caption_reserve_segment_order($1,1,6) AS value`, [run.run_id])).rows[0].value;
  assert.equal(Number(first.segment_order), 0);
  assert.equal(Number(second.segment_order), 1);
  const source = { segmentId: first.segment_id, segmentOrder: 0, sourceRevision: 1, text: '待翻譯原文', status: 'final', providerItemId: 'provider-1' };
  await db.query(`SELECT caption_checkpoint_source($1,1,6,$2::jsonb)`, [run.run_id, JSON.stringify(source)]);
  const pending = (await db.query(`SELECT caption_recover_pending($1,100) AS value`, [run.run_id])).rows[0].value;
  assert.equal(pending.finalSources.length, 1);
  assert.equal(pending.finalSources[0].text, '待翻譯原文');
  const context = (await db.query(`SELECT caption_runtime_context($1,1,6) AS value`, [run.run_id])).rows[0].value;
  assert.equal(context.recentSources[0].providerItemId, 'provider-1');
  assert.deepEqual(context.messageSeqByLanguage, {});
});

test('manual source allocation cannot collide with a later reserved ASR segment', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Manual order','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`,[event.event_id])).rows[0].value;
  const manual = (await db.query(`SELECT caption_manual_publish($1,'en','Fallback text',NULL) AS value`,[run.run_id])).rows[0].value;
  assert.equal(Number(manual.segment_order),0);
  await db.query(`UPDATE caption_runs SET fencing_token=2,lease_expires_at=now()+interval '5 minutes' WHERE id=$1`,[run.run_id]);
  const reserved = (await db.query(`SELECT caption_reserve_segment_order($1,1,2) AS value`,[run.run_id])).rows[0].value;
  assert.equal(Number(reserved.segment_order),1);
  await db.query(`SELECT caption_checkpoint_source($1,1,2,$2::jsonb)`,[run.run_id,JSON.stringify({segmentId:reserved.segment_id,segmentOrder:1,sourceRevision:1,text:'ASR source',status:'final'})]);
  const orders = await db.query(`SELECT segment_order FROM caption_source_segments WHERE run_id=$1 ORDER BY segment_order`,[run.run_id]);
  assert.deepEqual(orders.rows.map(row=>Number(row.segment_order)),[0,1]);
});

test('manual correction payload carries the persisted source and caption revisions', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event = (await db.query(`SELECT caption_create_event('Manual revisions','{}') AS value`)).rows[0].value;
  const run = (await db.query(`SELECT caption_start_run($1,'live') AS value`,[event.event_id])).rows[0].value;
  const sid='88888888-8888-4888-8888-888888888888';
  await db.query(`INSERT INTO caption_source_segments(run_id,segment_id,segment_order,source_revision,text,status) VALUES($1,$2,0,3,'source v3','final')`,[run.run_id,sid]);
  await db.query(`INSERT INTO caption_captions(run_id,segment_id,language,text,status,caption_revision,source_revision,origin) VALUES($1,$2,'en','AI v3','final',3,3,'ai_live')`,[run.run_id,sid]);
  const result=(await db.query(`SELECT caption_manual_publish($1,'en','Corrected',$2) AS value`,[run.run_id,sid])).rows[0].value;
  assert.equal(Number(result.source_revision),3);
  assert.equal(Number(result.caption_revision),4);
  const outbox=await db.query(`SELECT payload FROM caption_outbox_events WHERE id=$1`,[result.delivery_outbox_ids[0]]);
  assert.equal(Number(outbox.rows[0].payload.updates[0].sourceRevision),3);
  assert.equal(Number(outbox.rows[0].payload.updates[0].captionRevision),4);
});

test('pause atomically queues three status messages and HTTP claim skips stale generation or fence', async t => {
  const db = await database();
  t.after(() => db.close());
  await asService(db);
  const event=(await db.query(`SELECT caption_create_event('Status dispatch','{}') AS value`)).rows[0].value;
  const run=(await db.query(`SELECT caption_start_run($1,'live') AS value`,[event.event_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=7,channel_epoch='99999999-9999-4999-8999-999999999999' WHERE id=$1`,[run.run_id]);
  const paused=(await db.query(`SELECT caption_transition_run($1,'pause') AS value`,[run.run_id])).rows[0].value;
  assert.equal(paused.delivery_outbox_ids.length,3);
  const claimed=await db.query(`SELECT * FROM caption_claim_http_outbox($1::uuid[],'http-worker')`,[paused.delivery_outbox_ids]);
  assert.equal(claimed.rows.length,3);
  assert.deepEqual(claimed.rows.map(row=>row.payload.status).sort(),['paused','paused','paused']);
  for(const row of claimed.rows) await db.query(`SELECT caption_complete_outbox($1,'http-worker',NULL)`,[row.id]);
  const statuses=await db.query(`SELECT status,count(*)::int count FROM caption_outbox_events GROUP BY status`);
  assert.deepEqual(statuses.rows[0],{status:'sent',count:3});

  await db.query(`SELECT caption_transition_run($1,'resume')`,[run.run_id]);
  const manual=(await db.query(`SELECT caption_manual_publish($1,'en','Will become stale',NULL) AS value`,[run.run_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=fencing_token+1 WHERE id=$1`,[run.run_id]);
  const stale=await db.query(`SELECT * FROM caption_claim_http_outbox($1::uuid[],'http-worker-2')`,[manual.delivery_outbox_ids]);
  assert.equal(stale.rows.length,0);
  const stillQueued=await db.query(`SELECT status FROM caption_outbox_events WHERE id=$1`,[manual.delivery_outbox_ids[0]]);
  assert.equal(stillQueued.rows[0].status,'pending');
});

test('late AI rejected by a corrected caption cannot enqueue or replace the reducer value', async t => {
  const db=await database();
  t.after(()=>db.close());
  await asService(db);
  const event=(await db.query(`SELECT caption_create_event('Correction outbox','{}') AS value`)).rows[0].value;
  const run=(await db.query(`SELECT caption_start_run($1,'live') AS value`,[event.event_id])).rows[0].value;
  await db.query(`UPDATE caption_runs SET fencing_token=4,lease_expires_at=now()+interval '5 minutes' WHERE id=$1`,[run.run_id]);
  const sid='99999999-9999-4999-8999-999999999999';
  await db.query(`INSERT INTO caption_source_segments(run_id,segment_id,segment_order,source_revision,text,status) VALUES($1,$2,0,3,'source corrected','corrected')`,[run.run_id,sid]);
  await db.query(`INSERT INTO caption_captions(run_id,segment_id,language,text,status,caption_revision,source_revision,origin) VALUES($1,$2,'en','CORRECTED','corrected',4,3,'manual')`,[run.run_id,sid]);
  const late={language:'en',text:'LATE AI',status:'final',captionRevision:4,sourceRevision:4,origin:'ai_live'};
  const payload={schemaVersion:1,type:'caption.batch',eventId:event.event_id,runId:run.run_id,modeGeneration:1,channelEpoch:run.channel_epoch,messageSeq:1,language:'en',updates:[{segmentId:sid,segmentOrder:0,...late}]};
  const persisted=(await db.query(`SELECT caption_persist_final_and_enqueue($1,1,4,$2::jsonb,$3::jsonb,$4::jsonb,'late-ai') AS value`,[
    run.run_id,JSON.stringify({segmentId:sid,segmentOrder:0,sourceRevision:4,text:'source late',status:'final'}),
    JSON.stringify([late]),JSON.stringify([{language:'en',idempotencyKey:'late-ai-en',payload}])])).rows[0].value;
  assert.equal(persisted.outbox_count,0);
  assert.equal((await db.query(`SELECT count(*)::int count FROM caption_outbox_events WHERE run_id=$1`,[run.run_id])).rows[0].count,0);
  const stored=await db.query(`SELECT text,status,source_revision,caption_revision FROM caption_captions WHERE run_id=$1 AND segment_id=$2 AND language='en'`,[run.run_id,sid]);
  assert.deepEqual(stored.rows[0],{text:'CORRECTED',status:'corrected',source_revision:3,caption_revision:4});
  const snapshot=(await db.query(`SELECT caption_snapshot($1,$2,'en') AS value`,[event.event_id,run.run_id])).rows[0].value;
  const reducer=new Live.CaptionStore();
  assert.equal(reducer.merge(snapshot),true);
  assert.equal(reducer.segments('en')[0].text,'CORRECTED');
});

test('outbox recovery skips paused status instead of relabelling it as current live state', async t=>{
  const db=await database();
  t.after(()=>db.close());
  await asService(db);
  const event=(await db.query(`SELECT caption_create_event('State recovery','{}') AS value`)).rows[0].value;
  const run=(await db.query(`SELECT caption_start_run($1,'live') AS value`,[event.event_id])).rows[0].value;
  await db.query(`SELECT caption_transition_run($1,'pause')`,[run.run_id]);
  await db.query(`SELECT caption_transition_run($1,'resume')`,[run.run_id]);
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false); SELECT set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',false); SELECT set_config('request.jwt.claim.email','christychowtc@gmail.com',false);`);
  const ticket=(await db.query(`SELECT caption_issue_uplink_ticket($1,'https://wedding.test') AS value`,[run.run_id])).rows[0].value;
  const claimed=await db.query(`SELECT * FROM caption_claim_outbox($1,10,'gateway-current',3,$2)`,[run.run_id,ticket.fencing_token]);
  assert.equal(claimed.rows.length,3);
  for(const row of claimed.rows){
    assert.equal(row.payload.status,'live');
    assert.equal(Number(row.payload.modeGeneration),3);
    assert.equal(row.payload.channelEpoch,ticket.channel_epoch);
  }
  const skipped=await db.query(`SELECT count(*)::int count FROM caption_outbox_events WHERE run_id=$1 AND last_error_code='STALE_STATE_SKIPPED'`,[run.run_id]);
  assert.equal(skipped.rows[0].count,3);
  const en=claimed.rows.find(row=>row.language==='en');
  const reducer=new Live.CaptionStore();
  assert.equal(reducer.merge(en.payload),true);
  assert.equal(reducer.status,'live');
});

test('authorized old-run snapshot identifies the event current run without changing old history', async t=>{
  const db=await database();
  t.after(()=>db.close());
  await asService(db);
  const event=(await db.query(`SELECT caption_create_event('Run rollover','{}') AS value`)).rows[0].value;
  const oldRun=(await db.query(`SELECT caption_start_run($1,'live') AS value`,[event.event_id])).rows[0].value;
  const invite=(await db.query(`SELECT caption_create_invite($1,now()+interval '1 day',2) AS value`,[event.event_id])).rows[0].value;
  const userId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false); SELECT set_config('request.jwt.claim.sub','${userId}',false); SELECT set_config('request.jwt.claim.email','guest@example.com',false);`);
  await db.query(`SELECT caption_redeem_invite($1,$2)`,[event.event_id,invite.token]);
  await asService(db);
  await db.query(`SELECT caption_transition_run($1,'end')`,[oldRun.run_id]);
  const newRun=(await db.query(`SELECT caption_start_run($1,'live') AS value`,[event.event_id])).rows[0].value;
  const other=(await db.query(`SELECT caption_create_event('Other event','{}') AS value`)).rows[0].value;
  const otherRun=(await db.query(`SELECT caption_start_run($1,'live') AS value`,[other.event_id])).rows[0].value;
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false); SELECT set_config('request.jwt.claim.sub','${userId}',false); SELECT set_config('request.jwt.claim.email','guest@example.com',false);`);
  const snapshot=(await db.query(`SELECT caption_snapshot($1,$2,'en') AS value`,[event.event_id,oldRun.run_id])).rows[0].value;
  assert.equal(snapshot.runId,oldRun.run_id);
  assert.equal(snapshot.currentRunId,newRun.run_id);
  assert.deepEqual(snapshot.updates,[]);
  await assert.rejects(db.query(`SELECT caption_snapshot($1,$2,'en')`,[other.event_id,otherRun.run_id]),/caption membership required/);
});
